#:schema node_modules/wrangler/config-schema.json
name = "wandering-paths-record-v3"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/worker.js"

# Static assets configuration
[assets]
directory = "./dist/client"

# Environment variables (non-sensitive)
[vars]
SUPABASE_URL = "https://drtjfbvudzacixvqkzav.supabase.co"
AUTHORIZED_ADMIN_EMAIL = "magnus.hultberg@gmail.com"

# Custom domain configuration - force fresh route binding
[[routes]]
pattern = "restaurants.hultberg.org/"
zone_name = "hultberg.org"

[[routes]]
pattern = "restaurants.hultberg.org/*"
zone_name = "hultberg.org"

# Force cache invalidation
[analytics]
enabled = true

# Enable logging
[observability]
enabled = true