#:schema node_modules/wrangler/config-schema.json
name = "wandering-paths-record"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/worker.js"

# Environment variables (non-sensitive)
[vars]
SUPABASE_URL = "https://drtjfbvudzacixvqkzav.supabase.co"
AUTHORIZED_ADMIN_EMAIL = "magnus.hultberg@gmail.com"

# Custom domain configuration
[[routes]]
pattern = "restaurants.hultberg.org/*"
zone_name = "hultberg.org"